[package]
name = "hexerator"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
gamedebug_core = { git = "https://github.com/crumblingstatue/gamedebug_core.git", version = "0.1.0" }
clap = { version = "3.2.17", features = ["derive"] }
anyhow = "1.0.62"
rfd = "0.10.0"
rand = "0.8.5"
rmp-serde = "1.1.0"
serde = { version = "1.0.143", features = ["derive"] }
directories = "4.0.1"
recently_used_list = { git = "https://github.com/crumblingstatue/recently_used_list.git" }
memchr = "2.5.0"
glu-sys = "0.1.4"
thiserror = "1.0.32"
either = "1.8.0"
tree_magic_mini = { version = "3.0.3", features = ["tree_magic_db"] }
bytemuck = "1.12.1"
egui_easy_mark_standalone = { git = "https://github.com/crumblingstatue/egui-easymark-standalone.git", version = "0.1.0" }
index_many = "0.6.1"
slotmap = { version = "1.0.6", features = ["serde"] }
egui-sfml = "0.1.1"
num-traits = "0.2.15"
serde_with = "2.0.0"
serde-big-array = "0.4.1"
egui_extras = { version = "0.19.0", default-features = false }
rlua = "0.19.4"
itertools = "0.10.3"
sysinfo = { version = "0.26.2", default-features = false }
proc-maps = "0.2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Compile deps with optimizations in dev mode
[profile.dev.package."*"]
opt-level = 2
