[package]
name = "hexerator"
version = "0.1.0"
edition = "2021"

[dependencies]
gamedebug_core = { git = "https://github.com/crumblingstatue/gamedebug_core.git", version = "0.1.0" }
clap = { version = "3.2.7", features = ["derive"] }
anyhow = "1.0.58"
rfd = "0.9.1"
rand = "0.8.5"
rmp-serde = "1.1.0"
serde = { version = "1.0.137", features = ["derive"] }
# Need git version because 1.1.1 blocks on 2nd listener.accept() on windows
interprocess = { git = "https://github.com/kotauskas/interprocess.git", default-features = false }
directories = "4.0.1"
recently_used_list = { git = "https://github.com/crumblingstatue/recently_used_list.git" }
memchr = "2.5.0"
glu-sys = "0.1.4"
thiserror = "1.0.31"
either = "1.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml.git"
default-features = false
features = ["graphics"]

[dependencies.egui-sfml]
git = "https://github.com/crumblingstatue/egui-sfml.git"
